### ISSUE TITLE
Automatic update not working, because -utc string not exists in pine.json

### ISSUE THREAD

**Issue by Ajtak** [TTTT55/Lineage-OTA#1]
Automatic update not working, because **-utc** string not exists in pine.json

First URL is from pine.json file, second address is real github download URL:
```
https://github.com/TTTT55/Lineage-OTA/releases/download/pine-20210525/lineage-18.1-20210525-UNOFFICIAL-pine.zip
https://github.com/TTTT55/Lineage-OTA/releases/download/pine-20210525-utc/lineage-18.1-20210525-UNOFFICIAL-pine.zip
```
In the second url, there is also the string **-utc** 

Please check it, and fix it.

Thanks

**Comment by TTTT55** [comment]
That's not an issue. I said you'll get updates of the next builds in updater app.
