### ISSUE TITLE
Bootloop

### ISSUE THREAD

**Issue by SangenBR** [TTTT55/Lineage-OTA#2]
In the last two updates my cell goes into bootloop so I have to come back with backup, is there any tip or way that doesn't happen?

**Comment by hibikidesuuu** [comment]
> In the last two updates my cell goes into bootloop so I have to come back with backup, is there any tip or way that doesn't happen?

Mine had the same problem. I did a dirty flash and it only goes to the boot animation and after sometime it goes to twrp. what I did was, I flashed the gapps and magisk that was previously flashed before updating the system, wiped dalvic cache and it boot up normally without having to format all of my data. hope this helps!

**Comment by SangenBR** [comment]
> > In the last two updates my cell goes into bootloop so I have to come back with backup, is there any tip or way that doesn't happen?
> 
> Mine had the same problem. I did a dirty flash and it only goes to the boot animation and after sometime it goes to twrp. what I did was, I flashed the gapps and magisk that was previously flashed before updating the system, wiped dalvic cache and it boot up normally without having to format all of my data. hope this helps!

It worked, thank you very much.

**Comment by TTTT55** [comment]
It's an usual thing if you're using NikGapps. It seems NikGapps's OTA survival script is somewhat broken. You need to format data to get rid of bootloop or if you don't want to lose your data, then you can follow the steps given by @hibikidesuuu 
So now that you've got the fix I am closing this issue here
